apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: custom.rules
      rules:
 
        - alert: HighCPUUsage
          expr: avg(rate(container_cpu_usage_seconds_total{namespace="default", container!="", image!=""}[5m])) * 100 > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "CPU usage above 80% for 2 minutes."
 
        - alert: PodRestartingFrequently
          expr: increase(kube_pod_container_status_restarts_total{namespace="default"}[5m]) > 2
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod restarting frequently"
            description: "Pod restarted more than 2 times in 5 minutes."
