name: Java CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GUARDIAN_URL: ${{secrets.GUARDIAN_URL}}
      GUARDIAN_TOKEN: ${{secrets.GUARDIAN_TOKEN}}

      IMAGE_TAG: ${{github.run_number}}
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED for Sonar


      - name: Create metadata for Guardian
        shell: bash
        run: |
          cat <<EOF > metadata.json
          {
            "source": "github-actions",
            "repo": "${{ github.repository }}",
            "workflow": "${{ github.workflow }}",
            "job": "build",
            "run_id": "${{ github.run_id }}",
            "run_number": "${{ github.run_number }}",
            "run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "branch": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "actor": "${{ github.actor }}"
          }
          EOF

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Test (save logs)
        id: build_test
        shell: bash
        run: |
          set +e
          mvn clean verify 2>&1 | tee maven.log
          exit_code=${PIPESTATUS[0]}
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          exit 0

      - name: SonarCloud Analysis
        if: steps.build_test.outputs.exit_code == '0'
        run: mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Deploy Artifact to JFrog
        if: steps.build_test.outputs.exit_code == '0'
        run: mvn deploy --settings .mvn/settings.xml
        env:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}

      - name: Configure AWS Credentials
        if: steps.build_test.outputs.exit_code == '0'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      - name: Login to Amazon ECR
        if: steps.build_test.outputs.exit_code == '0'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
 
      - name: Build Docker image
        if: steps.build_test.outputs.exit_code == '0'
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }} .     

      - name: Scan Docker Image with Trivy
        if: steps.build_test.outputs.exit_code == '0' && env.docker_exit_code == '0'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
 
      - name: Tag Docker image
        if: steps.build_test.outputs.exit_code == '0' && env.docker_exit_code == '0'
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }} \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}
 
      - name: Push Docker image
        if: steps.build_test.outputs.exit_code == '0' && env.docker_exit_code == '0'
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}

      - name: Update kubeconfig
        if: steps.build_test.outputs.exit_code == '0' && env.docker_exit_code == '0'
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
 
      - name: Deploy to EKS
        if: steps.build_test.outputs.exit_code == '0' && env.docker_exit_code == '0'
        run: |
          kubectl set image deployment/petclinic-deployment petclinic=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}

      - name: Wait for deployment rollout
        run: |
          kubectl rollout status deployment/petclinic-deployment --timeout=180s

      - name: Wait for LoadBalancer to be ready
        run: |
          echo "Waiting for LoadBalancer..."
          for i in {1..30}; do
            LB=$(kubectl get svc petclinic-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            if [ -n "$LB" ]; then
              echo "LoadBalancer found: $LB"
              echo "APP_URL=http://$LB" >> $GITHUB_ENV
              break
            fi
            echo "Still waiting..."
            sleep 10
          done

          # Fail the step if LB is still empty after retries
          if [ -z "$LB" ]; then
            echo "LoadBalancer not ready after waiting."
            exit 1
          fi

      
      - name: Wait for app to be reachable via LoadBalancer
        run: |
          echo "Waiting for app URL to respond: $APP_URL"
          for i in {1..40}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 "$APP_URL" || true)
            echo "Attempt $i: HTTP $code"
            if [ "$code" = "200" ]; then
              echo "App is reachable!"
              exit 0
            fi
            sleep 10
          done
          echo "App did not become reachable in time"
          exit 1

          
      - name: Smoke Test Homepage (verbose)
        run: |
          curl -v --http1.1 --connect-timeout 10 --max-time 20 \
               --retry 10 --retry-delay 6 --retry-all-errors \
               "$APP_URL"

      
      - name: Rollback if smoke test fails
        if: failure()
        run: |
          echo "Smoke test failed. Rolling back..."
          kubectl rollout undo deployment/petclinic-deployment
          kubectl rollout status deployment/petclinic-deployment --timeout=180s
